# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  delib,
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}:
delib.host {
  name = "corn";

  nixos = {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot = {
      initrd.availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "ahci"
        "usbhid"
        "usb_storage"
        "sd_mod"
      ];
      initrd.kernelModules = [ ];

      blacklistedKernelModules = [ ];
      kernelModules = [
        "kvm-amd"
        "nct6775"
        "asus-ec-sensors"
        "asus_rog_ryujin"
      ];

      extraModulePackages = [
        (pkgs.callPackage ../../kernel-packages/asus-ec-sensors {
          kernel = config.boot.kernelPackages.kernel;
        })
        (pkgs.callPackage ../../kernel-packages/asus_rog_ryujin {
          kernel = config.boot.kernelPackages.kernel;
        })
      ];
    };

    # boot.kernelParams = [
    #   # try to fix samsung nvme failure after waking up from suspend
    #   "nvme_core.default_ps_max_latency_us=0"
    # ];

    services.udev.packages = [
      # https://support.system76.com/articles/kernelstub/
      (pkgs.writeTextDir "etc/udev/rules.d/99-nvme-tolerance.rules" ''
        ACTION=="add", SUBSYSTEM=="nvme", KERNEL=="nvme0", ATTR{power/pm_qos_latency_tolerance_us}="13500"
        ACTION=="add", SUBSYSTEM=="nvme", KERNEL=="nvme1", ATTR{power/pm_qos_latency_tolerance_us}="11000"
      '')
      (pkgs.writeTextDir "etc/udev/rules.d/99-ram-stick-detection.rules" ''
        ACTION=="add", SUBSYSTEM=="i2c", ATTR{name}=="SMBus PIIX4 adapter port 0 at 0b00", RUN+="${pkgs.bash}/bin/sh -c 'echo spd5118 0x53 > /sys/bus/i2c/devices/i2c-6/new_device'"
      '')
    ];

    fileSystems."/" = {
      device = "/dev/disk/by-label/NIX_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

    fileSystems."/home" = {
      device = "/dev/disk/by-label/NIX_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

    fileSystems."/persist" = {
      device = "/dev/disk/by-label/NIX_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

    fileSystems."/nix" = {
      device = "/dev/disk/by-label/NIX_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-label/NIX_BOOT";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    swapDevices = [
      { device = "/dev/disk/by-label/NIX_SWAP"; }
    ];

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.br0.useDHCP = lib.mkDefault true;
    # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
