# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  _pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@persist" ];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@var" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@nix" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/968c8b7a-52ef-4f27-9252-c282a67bc3f8";
    fsType = "btrfs";
    options = [ "subvol=@var/log" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4DF2-F4BC";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/d55c66de-36d0-4d00-abb1-90b5294bd8c6"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
