# https://github.com/NixOS/nixos-hardware/blob/master/asus/zenbook/ux371/default.nix
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  delib,
  config,
  lib,
  modulesPath,
  inputs,
  ...
}:
delib.host {
  name = "sesame";

  nixos = {
    imports = [
      inputs.asus-numberpad-driver.nixosModules.default
    ];

    services.asus-numberpad-driver = {
      enable = true;
      layout = "up5401ea";
      wayland = true;
      runtimeDir = "/run/user/1000/";
      waylandDisplay = "wayland-0";
      ignoreWaylandDisplayEnv = false;
      config = {
        # e.g. "activation_time" = "0.5";
        # More Configuration Options
      };
    };
  };
}
